version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datasherlocks-app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./models:/app/models
      - ./embeddings:/app/embeddings
      - ./index:/app/index
    ports:
      - "8501:8501"  # Streamlit port
      - "5000:5000"  # FastAPI port (optional)
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: datasherlocks-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    restart: unless-stopped

  # Optional Redis cache for better performance
  redis:
    image: redis:alpine
    container_name: datasherlocks-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: datasherlocks-network
    driver: bridge